name: spotless
on: [pull_request]

jobs:
  fix_formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Fetch refs
        run: git fetch origin master
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: run spotless
        run: ./gradlew spotlessApply
      - uses: stefanzweifel/git-auto-commit-action@v5
